# Generated by Django 3.1.7 on 2021-02-21 22:32

import datetime
from django.db import migrations, models
import gallery.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('picture', models.ImageField(default='gallery/static/gallery/pictures/default/no-img.jpg', upload_to=gallery.models.Image.path_and_rename)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 21, 22, 32, 18, 729729), verbose_name='Date added')),
                ('SFW', models.BooleanField(default=True)),
                ('url', models.CharField(default='http://localhost:8000/id/1337', max_length=200)),
                ('category', models.ManyToManyField(to='gallery.ImageCategory', verbose_name='Category')),
            ],
        ),
    ]
